// ============================================================================
//  Documents — seed data (in-memory)
// ----------------------------------------------------------------------------
//  Comprehensive seed data for all 8 documents sections:
//  Dashboard, Employee Documents, HR Documents, Document Library,
//  Document Requests, Generated Documents, Settings, Logs.
//  Mimics what the Prisma database would return.
// ============================================================================

import {
  EmployeeDoc, HRDoc, DocumentTemplate, DocumentRequest, GeneratedDoc,
  DocumentLog, EntityDocumentConfig, DocumentStatus,
} from "./shared"

const now = new Date()
const daysAgo = (n: number) => new Date(now.getTime() - n * 86400000).toISOString()
const daysAhead = (n: number) => new Date(now.getTime() + n * 86400000).toISOString()
const hoursAgo = (n: number) => new Date(now.getTime() - n * 3600000).toISOString()

// ============================================================================
//  1. Employee Documents  (16 records — covers all 11 categories + statuses)
// ============================================================================
export const EMPLOYEE_DOCUMENTS: EmployeeDoc[] = [
  { id: "ed-1", employeeCode: "EMP-001", employeeName: "Aarav Sharma", entityId: "ent-1",
    entityName: "ACME India Pvt Ltd", department: "Engineering", designation: "Senior Software Engineer",
    documentName: "Aadhaar Card", category: "Identity", documentType: "Aadhaar Card",
    uploadedDate: daysAgo(420), uploadedBy: "Anita Desai", verifiedBy: "Anita Desai",
    verifiedDate: daysAgo(418), expiryDate: null, status: "Verified",
    fileSize: "412 KB", version: 1, remarks: "Linked with DigiLocker" },
  { id: "ed-2", employeeCode: "EMP-001", employeeName: "Aarav Sharma", entityId: "ent-1",
    entityName: "ACME India Pvt Ltd", department: "Engineering", designation: "Senior Software Engineer",
    documentName: "PAN Card", category: "Identity", documentType: "PAN Card",
    uploadedDate: daysAgo(420), uploadedBy: "Anita Desai", verifiedBy: "Anita Desai",
    verifiedDate: daysAgo(418), expiryDate: null, status: "Verified", fileSize: "256 KB", version: 1 },
  { id: "ed-3", employeeCode: "EMP-002", employeeName: "Priya Nair", entityId: "ent-1",
    entityName: "ACME India Pvt Ltd", department: "Human Resources", designation: "HR Manager",
    documentName: "Passport", category: "Identity", documentType: "Passport",
    uploadedDate: daysAgo(360), uploadedBy: "Anita Desai", verifiedBy: "Anita Desai",
    verifiedDate: daysAgo(358), expiryDate: daysAhead(48), status: "Expiring Soon",
    fileSize: "1.2 MB", version: 1, remarks: "Expires in < 2 months — renewal initiated" },
  { id: "ed-4", employeeCode: "EMP-003", employeeName: "Vikram Reddy", entityId: "ent-1",
    entityName: "ACME India Pvt Ltd", department: "Sales", designation: "Regional Sales Manager",
    documentName: "Driving License", category: "Identity", documentType: "Driving License",
    uploadedDate: daysAgo(290), uploadedBy: "Vikram Reddy", verifiedBy: null,
    verifiedDate: null, expiryDate: daysAgo(12), status: "Expired",
    fileSize: "640 KB", version: 1, remarks: "Expired — awaiting renewal upload" },
  { id: "ed-5", employeeCode: "EMP-004", employeeName: "Sneha Iyer", entityId: "ent-1",
    entityName: "ACME India Pvt Ltd", department: "Finance", designation: "Finance Analyst",
    documentName: "Address Proof — Voter ID", category: "Address", documentType: "Voter ID",
    uploadedDate: daysAgo(180), uploadedBy: "Sneha Iyer", verifiedBy: "Anita Desai",
    verifiedDate: daysAgo(178), expiryDate: null, status: "Verified", fileSize: "388 KB", version: 1 },
  { id: "ed-6", employeeCode: "EMP-005", employeeName: "Rahul Verma", entityId: "ent-1",
    entityName: "ACME India Pvt Ltd", department: "Engineering", designation: "DevOps Engineer",
    documentName: "B.Tech Degree Certificate", category: "Education", documentType: "Education Certificate",
    uploadedDate: daysAgo(140), uploadedBy: "Rahul Verma", verifiedBy: null,
    verifiedDate: null, expiryDate: null, status: "Pending Verification", fileSize: "2.1 MB", version: 1 },
  { id: "ed-7", employeeCode: "EMP-006", employeeName: "Kavya Patel", entityId: "ent-1",
    entityName: "ACME India Pvt Ltd", department: "Product", designation: "Product Manager",
    documentName: "Previous Employer — Relieving Letter", category: "Experience", documentType: "Relieving Letter",
    uploadedDate: daysAgo(120), uploadedBy: "Kavya Patel", verifiedBy: "Anita Desai",
    verifiedDate: daysAgo(118), expiryDate: null, status: "Verified", fileSize: "512 KB", version: 1 },
  { id: "ed-8", employeeCode: "EMP-007", employeeName: "Arjun Mehta", entityId: "ent-1",
    entityName: "ACME India Pvt Ltd", department: "Engineering", designation: "Backend Engineer",
    documentName: "HDFC Bank Passbook", category: "Bank", documentType: "Bank Proof",
    uploadedDate: daysAgo(95), uploadedBy: "Arjun Mehta", verifiedBy: "Anita Desai",
    verifiedDate: daysAgo(93), expiryDate: null, status: "Verified", fileSize: "780 KB", version: 1 },
  { id: "ed-9", employeeCode: "EMP-008", employeeName: "Diya Kapoor", entityId: "ent-1",
    entityName: "ACME India Pvt Ltd", department: "Design", designation: "UX Designer",
    documentName: "Cancelled Cheque", category: "Bank", documentType: "Cancelled Cheque",
    uploadedDate: daysAgo(60), uploadedBy: "Diya Kapoor", verifiedBy: null,
    verifiedDate: null, expiryDate: null, status: "Uploaded", fileSize: "180 KB", version: 1 },
  { id: "ed-10", employeeCode: "EMP-009", employeeName: "Rohan Gupta", entityId: "ent-1",
    entityName: "ACME India Pvt Ltd", department: "Engineering", designation: "QA Lead",
    documentName: "Form 16 — FY 2023-24", category: "Statutory", documentType: "Form 16",
    uploadedDate: daysAgo(40), uploadedBy: "Rohan Gupta", verifiedBy: "Rajesh Kumar",
    verifiedDate: daysAgo(38), expiryDate: null, status: "Verified", fileSize: "1.4 MB", version: 1 },
  { id: "ed-11", employeeCode: "EMP-010", employeeName: "Ishaan Bose", entityId: "ent-1",
    entityName: "ACME India Pvt Ltd", department: "Operations", designation: "Operations Lead",
    documentName: "Appointment Letter", category: "Employment Letters", documentType: "Appointment Letter",
    uploadedDate: daysAgo(220), uploadedBy: "System", verifiedBy: "Anita Desai",
    verifiedDate: daysAgo(219), expiryDate: null, status: "Verified", fileSize: "320 KB", version: 2 },
  { id: "ed-12", employeeCode: "EMP-011", employeeName: "Ananya Singh", entityId: "ent-1",
    entityName: "ACME India Pvt Ltd", department: "Engineering", designation: "Frontend Engineer",
    documentName: "Salary Slip — Oct 2024", category: "Payroll", documentType: "Payslip",
    uploadedDate: daysAgo(25), uploadedBy: "System", verifiedBy: null,
    verifiedDate: null, expiryDate: null, status: "Pending Verification", fileSize: "240 KB", version: 1 },
  { id: "ed-13", employeeCode: "EMP-012", employeeName: "Fatima Al-Sayed", entityId: "ent-2",
    entityName: "ACME UAE FZE", department: "Sales", designation: "Sales Director — MENA",
    documentName: "Emirates ID", category: "Identity", documentType: "Emirates ID",
    uploadedDate: daysAgo(310), uploadedBy: "Layla Hassan", verifiedBy: "Layla Hassan",
    verifiedDate: daysAgo(308), expiryDate: daysAhead(120), status: "Verified", fileSize: "520 KB", version: 1 },
  { id: "ed-14", employeeCode: "EMP-013", employeeName: "Omar Khalid", entityId: "ent-2",
    entityName: "ACME UAE FZE", department: "Engineering", designation: "Cloud Architect",
    documentName: "Passport — UAE Visa Page", category: "Identity", documentType: "Passport",
    uploadedDate: daysAgo(280), uploadedBy: "Layla Hassan", verifiedBy: null,
    verifiedDate: null, expiryDate: daysAhead(15), status: "Expiring Soon",
    fileSize: "980 KB", version: 1, remarks: "Visa renewal initiated" },
  { id: "ed-15", employeeCode: "EMP-014", employeeName: "Emily Carter", entityId: "ent-3",
    entityName: "ACME US Inc", department: "Engineering", designation: "Engineering Manager",
    documentName: "SSN Card", category: "Statutory", documentType: "SSN Card",
    uploadedDate: daysAgo(190), uploadedBy: "Sarah Johnson", verifiedBy: "Sarah Johnson",
    verifiedDate: daysAgo(188), expiryDate: null, status: "Verified",
    fileSize: "300 KB", version: 1, remarks: "Masked in viewer" },
  { id: "ed-16", employeeCode: "EMP-015", employeeName: "Wei Lin", entityId: "ent-4",
    entityName: "ACME Singapore Pte Ltd", department: "Finance", designation: "Senior Accountant",
    documentName: "Employment Pass (EP)", category: "Compliance", documentType: "EP Pass",
    uploadedDate: daysAgo(160), uploadedBy: "Marcus Tan", verifiedBy: "Marcus Tan",
    verifiedDate: daysAgo(158), expiryDate: daysAhead(75), status: "Verified", fileSize: "610 KB", version: 1 },
]

// ============================================================================
//  2. HR Documents  (12 records — covers all 15 HR categories)
// ============================================================================
export const HR_DOCUMENTS: HRDoc[] = [
  { id: "hd-1", documentName: "Employee Handbook 2024", category: "Employee Handbook",
    entityId: "ent-1", entityName: "ACME India Pvt Ltd", department: null, visibleTo: "All Employees",
    uploadedDate: daysAgo(220), uploadedBy: "Anita Desai", version: "v4.2",
    acknowledgmentRequired: true, acknowledgmentDueDate: daysAhead(20), acknowledgmentRate: 88,
    status: "Published", fileSize: "8.4 MB",
    description: "Comprehensive guide covering all policies, benefits, culture & code of conduct" },
  { id: "hd-2", documentName: "POSH Policy 2024", category: "POSH Policy",
    entityId: "ent-1", entityName: "ACME India Pvt Ltd", department: null, visibleTo: "All Employees",
    uploadedDate: daysAgo(180), uploadedBy: "Anita Desai", version: "v3.0",
    acknowledgmentRequired: true, acknowledgmentDueDate: daysAhead(10), acknowledgmentRate: 96,
    status: "Published", fileSize: "1.2 MB",
    description: "Prevention of Sexual Harassment policy as per POSH Act 2013" },
  { id: "hd-3", documentName: "Leave Policy v3", category: "Leave Policy",
    entityId: "ent-1", entityName: "ACME India Pvt Ltd", department: null, visibleTo: "All Employees",
    uploadedDate: daysAgo(150), uploadedBy: "Anita Desai", version: "v3.1",
    acknowledgmentRequired: false, acknowledgmentRate: 0, status: "Published", fileSize: "640 KB",
    description: "Annual, sick, casual, privilege & comp-off leave rules" },
  { id: "hd-4", documentName: "Attendance & WFH Policy", category: "Attendance Policy",
    entityId: "ent-1", entityName: "ACME India Pvt Ltd", department: null, visibleTo: "All Employees",
    uploadedDate: daysAgo(140), uploadedBy: "Rajesh Kumar", version: "v2.0",
    acknowledgmentRequired: true, acknowledgmentDueDate: daysAhead(5), acknowledgmentRate: 72,
    status: "Published", fileSize: "420 KB",
    description: "Biometric, swipe, WFH eligibility & remote work hours" },
  { id: "hd-5", documentName: "Payroll & Compensation Policy", category: "Payroll Policy",
    entityId: "ent-1", entityName: "ACME India Pvt Ltd", department: null, visibleTo: "All Employees",
    uploadedDate: daysAgo(120), uploadedBy: "Rajesh Kumar", version: "v2.1",
    acknowledgmentRequired: false, acknowledgmentRate: 0, status: "Published", fileSize: "380 KB" },
  { id: "hd-6", documentName: "Travel & Visa Policy", category: "Travel Policy",
    entityId: "ent-1", entityName: "ACME India Pvt Ltd", department: null, visibleTo: "Selected Employee Type",
    uploadedDate: daysAgo(100), uploadedBy: "Anita Desai", version: "v1.4",
    acknowledgmentRequired: false, acknowledgmentRate: 0, status: "Published", fileSize: "560 KB" },
  { id: "hd-7", documentName: "Expense Reimbursement Policy", category: "Expense Policy",
    entityId: "ent-1", entityName: "ACME India Pvt Ltd", department: null, visibleTo: "All Employees",
    uploadedDate: daysAgo(95), uploadedBy: "Rajesh Kumar", version: "v1.8",
    acknowledgmentRequired: true, acknowledgmentDueDate: daysAhead(15), acknowledgmentRate: 64,
    status: "Published", fileSize: "290 KB" },
  { id: "hd-8", documentName: "IT Security & Data Protection Policy", category: "IT Policy",
    entityId: "ent-1", entityName: "ACME India Pvt Ltd", department: null, visibleTo: "All Employees",
    uploadedDate: daysAgo(80), uploadedBy: "Vikram Reddy", version: "v2.3",
    acknowledgmentRequired: true, acknowledgmentDueDate: daysAhead(7), acknowledgmentRate: 81,
    status: "Published", fileSize: "1.1 MB" },
  { id: "hd-9", documentName: "Asset Issuance & Return Policy", category: "Asset Policy",
    entityId: "ent-1", entityName: "ACME India Pvt Ltd", department: null, visibleTo: "All Employees",
    uploadedDate: daysAgo(70), uploadedBy: "Vikram Reddy", version: "v1.2",
    acknowledgmentRequired: false, acknowledgmentRate: 0, status: "Published", fileSize: "350 KB" },
  { id: "hd-10", documentName: "Code of Conduct 2024", category: "Code of Conduct",
    entityId: "ent-1", entityName: "ACME India Pvt Ltd", department: null, visibleTo: "All Employees",
    uploadedDate: daysAgo(60), uploadedBy: "Anita Desai", version: "v3.0",
    acknowledgmentRequired: true, acknowledgmentDueDate: daysAhead(2), acknowledgmentRate: 92,
    status: "Published", fileSize: "480 KB" },
  { id: "hd-11", documentName: "Onboarding Training Material — Engineering", category: "Training Material",
    entityId: "ent-1", entityName: "ACME India Pvt Ltd", department: "Engineering", visibleTo: "Selected Department",
    uploadedDate: daysAgo(30), uploadedBy: "Anita Desai", version: "v1.0",
    acknowledgmentRequired: false, acknowledgmentRate: 0, status: "Draft", fileSize: "12.6 MB" },
  { id: "hd-12", documentName: "Quarterly Company Circular Q3-2024", category: "Company Circular",
    entityId: "ent-1", entityName: "ACME India Pvt Ltd", department: null, visibleTo: "All Employees",
    uploadedDate: daysAgo(10), uploadedBy: "Anita Desai", version: "v1.0",
    acknowledgmentRequired: false, acknowledgmentRate: 0, status: "Unpublished", fileSize: "240 KB",
    description: "Awaiting final approval — Q3 town hall summary & org changes" },
]

// ============================================================================
//  3. Document Templates  (21 templates — covers all 20 template categories)
// ============================================================================
//  Each template merges module-availability + approval/sign/allow flags onto
//  condensed lines for compactness.
export const DOCUMENT_TEMPLATES: DocumentTemplate[] = [
  { id: "tpl-1", name: "India Offer Letter", code: "TPL-OFF-IND-001", category: "Offer Letter",
    entityId: "ent-1", entityName: "ACME India Pvt Ltd", createdDate: daysAgo(365),
    createdBy: "Anita Desai", updatedBy: "Anita Desai", version: "v2.1", isFavourite: true,
    status: "Active", availableForRequest: false, availableForHR: true, availableForOnboarding: true,
    availableForOffboarding: false, availableForPayroll: false,
    approvalRequired: true, eSignRequired: true, acknowledgmentRequired: true,
    allowDownload: true, allowEmail: true, allowPrint: true,
    description: "Standard India offer letter with CTC breakdown and joining terms",
    pageSize: "A4", orientation: "Portrait" },
  { id: "tpl-2", name: "UAE Offer Letter", code: "TPL-OFF-UAE-001", category: "Offer Letter",
    entityId: "ent-2", entityName: "ACME UAE FZE", createdDate: daysAgo(300),
    createdBy: "Layla Hassan", updatedBy: "Layla Hassan", version: "v1.3", isFavourite: false,
    status: "Active", availableForRequest: false, availableForHR: true, availableForOnboarding: true,
    availableForOffboarding: false, availableForPayroll: false,
    approvalRequired: true, eSignRequired: true, acknowledgmentRequired: true,
    allowDownload: true, allowEmail: true, allowPrint: true, pageSize: "A4", orientation: "Portrait" },
  { id: "tpl-3", name: "India Appointment Letter", code: "TPL-APP-IND-001", category: "Appointment Letter",
    entityId: "ent-1", entityName: "ACME India Pvt Ltd", createdDate: daysAgo(355),
    createdBy: "Anita Desai", updatedBy: "Anita Desai", version: "v2.0", isFavourite: true,
    status: "Active", availableForRequest: false, availableForHR: true, availableForOnboarding: true,
    availableForOffboarding: false, availableForPayroll: false,
    approvalRequired: true, eSignRequired: true, acknowledgmentRequired: true,
    allowDownload: true, allowEmail: true, allowPrint: true, pageSize: "A4", orientation: "Portrait" },
  { id: "tpl-4", name: "Confirmation Letter", code: "TPL-CONF-001", category: "Confirmation Letter",
    entityId: "ent-1", entityName: "ACME India Pvt Ltd", createdDate: daysAgo(280),
    createdBy: "Anita Desai", updatedBy: "Anita Desai", version: "v1.2", isFavourite: false,
    status: "Active", availableForRequest: false, availableForHR: true, availableForOnboarding: false,
    availableForOffboarding: false, availableForPayroll: false,
    approvalRequired: true, eSignRequired: false, acknowledgmentRequired: true,
    allowDownload: true, allowEmail: true, allowPrint: true, pageSize: "A4", orientation: "Portrait" },
  { id: "tpl-5", name: "Annual Increment Letter", code: "TPL-INCR-001", category: "Increment Letter",
    entityId: "ent-1", entityName: "ACME India Pvt Ltd", createdDate: daysAgo(245),
    createdBy: "Rajesh Kumar", updatedBy: "Rajesh Kumar", version: "v1.5", isFavourite: true,
    status: "Active", availableForRequest: false, availableForHR: true, availableForOnboarding: false,
    availableForOffboarding: false, availableForPayroll: true,
    approvalRequired: true, eSignRequired: true, acknowledgmentRequired: true,
    allowDownload: true, allowEmail: true, allowPrint: true, pageSize: "A4", orientation: "Portrait" },
  { id: "tpl-6", name: "Promotion Letter", code: "TPL-PROM-001", category: "Promotion Letter",
    entityId: "ent-1", entityName: "ACME India Pvt Ltd", createdDate: daysAgo(220),
    createdBy: "Anita Desai", updatedBy: "Anita Desai", version: "v1.1", isFavourite: false,
    status: "Active", availableForRequest: false, availableForHR: true, availableForOnboarding: false,
    availableForOffboarding: false, availableForPayroll: false,
    approvalRequired: true, eSignRequired: false, acknowledgmentRequired: true,
    allowDownload: true, allowEmail: true, allowPrint: true, pageSize: "A4", orientation: "Portrait" },
  { id: "tpl-7", name: "Transfer Letter", code: "TPL-TRNS-001", category: "Transfer Letter",
    entityId: "ent-1", entityName: "ACME India Pvt Ltd", createdDate: daysAgo(195),
    createdBy: "Anita Desai", updatedBy: "Anita Desai", version: "v1.0", isFavourite: false,
    status: "Active", availableForRequest: false, availableForHR: true, availableForOnboarding: false,
    availableForOffboarding: false, availableForPayroll: false,
    approvalRequired: true, eSignRequired: false, acknowledgmentRequired: true,
    allowDownload: true, allowEmail: true, allowPrint: true, pageSize: "A4", orientation: "Portrait" },
  { id: "tpl-8", name: "Internship Offer Letter", code: "TPL-INT-001", category: "Internship Letter",
    entityId: "ent-1", entityName: "ACME India Pvt Ltd", createdDate: daysAgo(180),
    createdBy: "Anita Desai", updatedBy: "Anita Desai", version: "v1.0", isFavourite: false,
    status: "Active", availableForRequest: false, availableForHR: true, availableForOnboarding: true,
    availableForOffboarding: false, availableForPayroll: false,
    approvalRequired: false, eSignRequired: false, acknowledgmentRequired: false,
    allowDownload: true, allowEmail: true, allowPrint: true, pageSize: "A4", orientation: "Portrait" },
  { id: "tpl-9", name: "Contract Letter — Contractor", code: "TPL-CON-001", category: "Contract Letter",
    entityId: "ent-1", entityName: "ACME India Pvt Ltd", createdDate: daysAgo(160),
    createdBy: "Anita Desai", updatedBy: "Anita Desai", version: "v1.2", isFavourite: false,
    status: "Active", availableForRequest: false, availableForHR: true, availableForOnboarding: true,
    availableForOffboarding: false, availableForPayroll: false,
    approvalRequired: true, eSignRequired: true, acknowledgmentRequired: true,
    allowDownload: true, allowEmail: true, allowPrint: true, pageSize: "A4", orientation: "Portrait" },
  { id: "tpl-10", name: "Warning Letter — Performance", code: "TPL-WARN-001", category: "Warning Letter",
    entityId: "ent-1", entityName: "ACME India Pvt Ltd", createdDate: daysAgo(150),
    createdBy: "Anita Desai", updatedBy: "Anita Desai", version: "v1.0", isFavourite: false,
    status: "Active", availableForRequest: false, availableForHR: true, availableForOnboarding: false,
    availableForOffboarding: false, availableForPayroll: false,
    approvalRequired: true, eSignRequired: false, acknowledgmentRequired: false,
    allowDownload: true, allowEmail: true, allowPrint: true, pageSize: "A4", orientation: "Portrait" },
  { id: "tpl-11", name: "Resignation Acceptance Letter", code: "TPL-RES-ACC-001", category: "Resignation Acceptance Letter",
    entityId: "ent-1", entityName: "ACME India Pvt Ltd", createdDate: daysAgo(140),
    createdBy: "Anita Desai", updatedBy: "Anita Desai", version: "v1.0", isFavourite: false,
    status: "Active", availableForRequest: false, availableForHR: true, availableForOnboarding: false,
    availableForOffboarding: true, availableForPayroll: false,
    approvalRequired: true, eSignRequired: false, acknowledgmentRequired: false,
    allowDownload: true, allowEmail: true, allowPrint: true, pageSize: "A4", orientation: "Portrait" },
  { id: "tpl-12", name: "Relieving Letter", code: "TPL-REL-001", category: "Relieving Letter",
    entityId: "ent-1", entityName: "ACME India Pvt Ltd", createdDate: daysAgo(130),
    createdBy: "Anita Desai", updatedBy: "Anita Desai", version: "v1.1", isFavourite: true,
    status: "Active", availableForRequest: true, availableForHR: true, availableForOnboarding: false,
    availableForOffboarding: true, availableForPayroll: false,
    approvalRequired: true, eSignRequired: true, acknowledgmentRequired: false,
    allowDownload: true, allowEmail: true, allowPrint: true, pageSize: "A4", orientation: "Portrait" },
  { id: "tpl-13", name: "Experience Letter", code: "TPL-EXP-001", category: "Experience Letter",
    entityId: "ent-1", entityName: "ACME India Pvt Ltd", createdDate: daysAgo(120),
    createdBy: "Anita Desai", updatedBy: "Anita Desai", version: "v1.0", isFavourite: true,
    status: "Active", availableForRequest: true, availableForHR: true, availableForOnboarding: false,
    availableForOffboarding: true, availableForPayroll: false,
    approvalRequired: true, eSignRequired: true, acknowledgmentRequired: false,
    allowDownload: true, allowEmail: true, allowPrint: true, pageSize: "A4", orientation: "Portrait" },
  { id: "tpl-14", name: "Termination Letter", code: "TPL-TERM-001", category: "Termination Letter",
    entityId: "ent-1", entityName: "ACME India Pvt Ltd", createdDate: daysAgo(100),
    createdBy: "Anita Desai", updatedBy: "Anita Desai", version: "v1.0", isFavourite: false,
    status: "Draft", availableForRequest: false, availableForHR: true, availableForOnboarding: false,
    availableForOffboarding: true, availableForPayroll: false,
    approvalRequired: true, eSignRequired: false, acknowledgmentRequired: false,
    allowDownload: true, allowEmail: true, allowPrint: true, pageSize: "A4", orientation: "Portrait" },
  { id: "tpl-15", name: "FnF Settlement Letter", code: "TPL-FNF-001", category: "FnF Settlement Letter",
    entityId: "ent-1", entityName: "ACME India Pvt Ltd", createdDate: daysAgo(80),
    createdBy: "Rajesh Kumar", updatedBy: "Rajesh Kumar", version: "v1.0", isFavourite: false,
    status: "Active", availableForRequest: false, availableForHR: true, availableForOnboarding: false,
    availableForOffboarding: true, availableForPayroll: true,
    approvalRequired: true, eSignRequired: true, acknowledgmentRequired: false,
    allowDownload: true, allowEmail: true, allowPrint: true, pageSize: "A4", orientation: "Portrait" },
  { id: "tpl-16", name: "Salary Certificate", code: "TPL-SAL-CERT-001", category: "Salary Certificate",
    entityId: "ent-1", entityName: "ACME India Pvt Ltd", createdDate: daysAgo(60),
    createdBy: "Rajesh Kumar", updatedBy: "Rajesh Kumar", version: "v1.2", isFavourite: true,
    status: "Active", availableForRequest: true, availableForHR: true, availableForOnboarding: false,
    availableForOffboarding: false, availableForPayroll: true,
    approvalRequired: true, eSignRequired: true, acknowledgmentRequired: false,
    allowDownload: true, allowEmail: true, allowPrint: true, pageSize: "A4", orientation: "Portrait" },
  { id: "tpl-17", name: "Employment Certificate", code: "TPL-EMP-CERT-001", category: "Employment Certificate",
    entityId: "ent-1", entityName: "ACME India Pvt Ltd", createdDate: daysAgo(55),
    createdBy: "Anita Desai", updatedBy: "Anita Desai", version: "v1.0", isFavourite: false,
    status: "Active", availableForRequest: true, availableForHR: true, availableForOnboarding: false,
    availableForOffboarding: false, availableForPayroll: false,
    approvalRequired: true, eSignRequired: false, acknowledgmentRequired: false,
    allowDownload: true, allowEmail: true, allowPrint: true, pageSize: "A4", orientation: "Portrait" },
  { id: "tpl-18", name: "Address Proof Letter", code: "TPL-ADDR-001", category: "Address Proof Letter",
    entityId: "ent-1", entityName: "ACME India Pvt Ltd", createdDate: daysAgo(50),
    createdBy: "Anita Desai", updatedBy: "Anita Desai", version: "v1.0", isFavourite: false,
    status: "Active", availableForRequest: true, availableForHR: true, availableForOnboarding: false,
    availableForOffboarding: false, availableForPayroll: false,
    approvalRequired: false, eSignRequired: false, acknowledgmentRequired: false,
    allowDownload: true, allowEmail: true, allowPrint: true, pageSize: "A4", orientation: "Portrait" },
  { id: "tpl-19", name: "Visa / Embassy Letter", code: "TPL-VISA-001", category: "Visa / Embassy Letter",
    entityId: "ent-1", entityName: "ACME India Pvt Ltd", createdDate: daysAgo(40),
    createdBy: "Anita Desai", updatedBy: "Anita Desai", version: "v1.0", isFavourite: false,
    status: "Active", availableForRequest: true, availableForHR: true, availableForOnboarding: false,
    availableForOffboarding: false, availableForPayroll: false,
    approvalRequired: true, eSignRequired: false, acknowledgmentRequired: false,
    allowDownload: true, allowEmail: true, allowPrint: true, pageSize: "A4", orientation: "Portrait" },
  { id: "tpl-20", name: "No Dues Certificate", code: "TPL-NDC-001", category: "No Dues Certificate",
    entityId: "ent-1", entityName: "ACME India Pvt Ltd", createdDate: daysAgo(30),
    createdBy: "Anita Desai", updatedBy: "Anita Desai", version: "v1.0", isFavourite: false,
    status: "Active", availableForRequest: true, availableForHR: true, availableForOnboarding: false,
    availableForOffboarding: true, availableForPayroll: false,
    approvalRequired: true, eSignRequired: false, acknowledgmentRequired: false,
    allowDownload: true, allowEmail: true, allowPrint: true, pageSize: "A4", orientation: "Portrait" },
  { id: "tpl-21", name: "Custom — Bonafide Letter", code: "TPL-CUST-001", category: "Custom Document",
    entityId: "ent-1", entityName: "ACME India Pvt Ltd", createdDate: daysAgo(15),
    createdBy: "Anita Desai", updatedBy: "Anita Desai", version: "v0.1", isFavourite: false,
    status: "Inactive", availableForRequest: false, availableForHR: true, availableForOnboarding: false,
    availableForOffboarding: false, availableForPayroll: false,
    approvalRequired: false, eSignRequired: false, acknowledgmentRequired: false,
    allowDownload: true, allowEmail: true, allowPrint: true, pageSize: "A4", orientation: "Portrait" },
]

// ============================================================================
//  4. Document Requests  (10 requests — covers all request statuses)
// ============================================================================
export const DOCUMENT_REQUESTS: DocumentRequest[] = [
  { id: "dr-1", requestId: "REQ-DOC-2024-001", employeeCode: "EMP-005",
    employeeName: "Rahul Verma", documentType: "Salary Certificate",
    entityId: "ent-1", entityName: "ACME India Pvt Ltd",
    reason: "Home Loan Application — HDFC Bank", addressedTo: "HDFC Bank",
    purpose: "Bank Loan", requestedDate: daysAgo(2), pendingWith: "Anita Desai (HR Manager)",
    status: "Pending HR Approval", slaDays: 3, slaRemaining: 1, attachment: true },
  { id: "dr-2", requestId: "REQ-DOC-2024-002", employeeCode: "EMP-006",
    employeeName: "Kavya Patel", documentType: "Employment Certificate",
    entityId: "ent-1", entityName: "ACME India Pvt Ltd",
    reason: "Visa Application — Schengen", addressedTo: "VFS Global",
    purpose: "Visa", requestedDate: daysAgo(5), pendingWith: "Anita Desai (HR Manager)",
    status: "Approved", slaDays: 3, slaRemaining: 0, attachment: false },
  { id: "dr-3", requestId: "REQ-DOC-2024-003", employeeCode: "EMP-008",
    employeeName: "Diya Kapoor", documentType: "Address Proof Letter",
    entityId: "ent-1", entityName: "ACME India Pvt Ltd",
    reason: "Passport Application — Address Change", addressedTo: "Passport Seva Kendra",
    purpose: "Government", requestedDate: daysAgo(8), pendingWith: "System (Auto-Approved)",
    status: "Generated", slaDays: 2, slaRemaining: 0, attachment: true },
  { id: "dr-4", requestId: "REQ-DOC-2024-004", employeeCode: "EMP-011",
    employeeName: "Ananya Singh", documentType: "Visa / Embassy Letter",
    entityId: "ent-1", entityName: "ACME India Pvt Ltd",
    reason: "US Business Visa — B1", addressedTo: "US Consulate Mumbai",
    purpose: "Visa", requestedDate: daysAgo(10), pendingWith: "Closed — Delivered",
    status: "Sent to Employee", slaDays: 5, slaRemaining: 0, attachment: true },
  { id: "dr-5", requestId: "REQ-DOC-2024-005", employeeCode: "EMP-013",
    employeeName: "Omar Khalid", documentType: "Salary Certificate",
    entityId: "ent-2", entityName: "ACME UAE FZE",
    reason: "Car Loan — Emirates NBD", addressedTo: "Emirates NBD",
    purpose: "Bank Loan", requestedDate: daysAgo(12), pendingWith: "Closed",
    status: "Closed", slaDays: 4, slaRemaining: 0, attachment: false },
  { id: "dr-6", requestId: "REQ-DOC-2024-006", employeeCode: "EMP-007",
    employeeName: "Arjun Mehta", documentType: "Bank Letter",
    entityId: "ent-1", entityName: "ACME India Pvt Ltd",
    reason: "Account opening — Axis Bank", addressedTo: "Axis Bank",
    purpose: "Bank", requestedDate: daysAgo(15), pendingWith: "Rejected by Anita Desai",
    status: "Rejected", slaDays: 3, slaRemaining: 0, attachment: false },
  { id: "dr-7", requestId: "REQ-DOC-2024-007", employeeCode: "EMP-014",
    employeeName: "Emily Carter", documentType: "NOC — Travel",
    entityId: "ent-3", entityName: "ACME US Inc",
    reason: "NOC for client travel to Canada", addressedTo: "Canada Border Services",
    purpose: "Travel", requestedDate: daysAgo(1), pendingWith: "Draft (not yet submitted)",
    status: "Submitted", slaDays: 5, slaRemaining: 4, attachment: false },
  { id: "dr-8", requestId: "REQ-DOC-2024-008", employeeCode: "EMP-015",
    employeeName: "Wei Lin", documentType: "Employment Certificate",
    entityId: "ent-4", entityName: "ACME Singapore Pte Ltd",
    reason: "Credit Card Application — DBS", addressedTo: "DBS Bank",
    purpose: "Bank Loan", requestedDate: hoursAgo(6), pendingWith: "Draft (employee)",
    status: "Draft", slaDays: 3, slaRemaining: 3, attachment: false },
  { id: "dr-9", requestId: "REQ-DOC-2024-009", employeeCode: "EMP-003",
    employeeName: "Vikram Reddy", documentType: "Relieving Letter (Previous)",
    entityId: "ent-1", entityName: "ACME India Pvt Ltd",
    reason: "Background verification — previous employer", addressedTo: "BGV Agency",
    purpose: "Reference", requestedDate: daysAgo(20), pendingWith: "Closed",
    status: "Closed", slaDays: 5, slaRemaining: 0, attachment: true },
  { id: "dr-10", requestId: "REQ-DOC-2024-010", employeeCode: "EMP-012",
    employeeName: "Fatima Al-Sayed", documentType: "Salary Certificate",
    entityId: "ent-2", entityName: "ACME UAE FZE",
    reason: "Mortgage — Mashreq Bank", addressedTo: "Mashreq Bank",
    purpose: "Bank Loan", requestedDate: daysAgo(7), pendingWith: "Anita Desai (overdue)",
    status: "Pending HR Approval", slaDays: 3, slaRemaining: -2, attachment: true },
]

// ============================================================================
//  5. Generated Documents  (14 records — all source modules represented)
// ============================================================================
export const GENERATED_DOCUMENTS: GeneratedDoc[] = [
  { id: "gd-1", generatedId: "GEN-DOC-2024-0001", documentName: "Offer Letter — Aarav Sharma",
    templateName: "India Offer Letter", employeeCode: "EMP-001", employeeName: "Aarav Sharma",
    entityId: "ent-1", entityName: "ACME India Pvt Ltd", generatedDate: daysAgo(420),
    generatedBy: "Anita Desai", sourceModule: "Onboarding", status: "Sent",
    fileSize: "180 KB", eSigned: true },
  { id: "gd-2", generatedId: "GEN-DOC-2024-0002", documentName: "Appointment Letter — Aarav Sharma",
    templateName: "India Appointment Letter", employeeCode: "EMP-001", employeeName: "Aarav Sharma",
    entityId: "ent-1", entityName: "ACME India Pvt Ltd", generatedDate: daysAgo(418),
    generatedBy: "Anita Desai", sourceModule: "Onboarding", status: "Downloaded",
    fileSize: "200 KB", eSigned: true },
  { id: "gd-3", generatedId: "GEN-DOC-2024-0003", documentName: "Offer Letter — Fatima Al-Sayed",
    templateName: "UAE Offer Letter", employeeCode: "EMP-012", employeeName: "Fatima Al-Sayed",
    entityId: "ent-2", entityName: "ACME UAE FZE", generatedDate: daysAgo(310),
    generatedBy: "Layla Hassan", sourceModule: "Onboarding", status: "Sent",
    fileSize: "190 KB", eSigned: true },
  { id: "gd-4", generatedId: "GEN-DOC-2024-0004", documentName: "Offer Letter — Emily Carter",
    templateName: "UAE Offer Letter", employeeCode: "EMP-014", employeeName: "Emily Carter",
    entityId: "ent-3", entityName: "ACME US Inc", generatedDate: daysAgo(190),
    generatedBy: "Sarah Johnson", sourceModule: "Onboarding", status: "Sent",
    fileSize: "195 KB", eSigned: false },
  { id: "gd-5", generatedId: "GEN-DOC-2024-0005", documentName: "Annual Increment Letter — Aarav Sharma",
    templateName: "Annual Increment Letter", employeeCode: "EMP-001", employeeName: "Aarav Sharma",
    entityId: "ent-1", entityName: "ACME India Pvt Ltd", generatedDate: daysAgo(35),
    generatedBy: "Rajesh Kumar", sourceModule: "Payroll", status: "Sent",
    fileSize: "210 KB", eSigned: true },
  { id: "gd-6", generatedId: "GEN-DOC-2024-0006", documentName: "Annual Increment Letter — Priya Nair",
    templateName: "Annual Increment Letter", employeeCode: "EMP-002", employeeName: "Priya Nair",
    entityId: "ent-1", entityName: "ACME India Pvt Ltd", generatedDate: daysAgo(35),
    generatedBy: "Rajesh Kumar", sourceModule: "Payroll", status: "Downloaded",
    fileSize: "210 KB", eSigned: true },
  { id: "gd-7", generatedId: "GEN-DOC-2024-0007", documentName: "Salary Certificate — Rahul Verma",
    templateName: "Salary Certificate", employeeCode: "EMP-005", employeeName: "Rahul Verma",
    entityId: "ent-1", entityName: "ACME India Pvt Ltd", generatedDate: hoursAgo(4),
    generatedBy: "System (Auto-Generated)", sourceModule: "Employee Request",
    status: "Generated", fileSize: "160 KB", eSigned: false },
  { id: "gd-8", generatedId: "GEN-DOC-2024-0008", documentName: "Address Proof Letter — Diya Kapoor",
    templateName: "Address Proof Letter", employeeCode: "EMP-008", employeeName: "Diya Kapoor",
    entityId: "ent-1", entityName: "ACME India Pvt Ltd", generatedDate: daysAgo(6),
    generatedBy: "Anita Desai", sourceModule: "Employee Request", status: "Sent",
    fileSize: "150 KB", eSigned: false },
  { id: "gd-9", generatedId: "GEN-DOC-2024-0009", documentName: "Visa / Embassy Letter — Ananya Singh",
    templateName: "Visa / Embassy Letter", employeeCode: "EMP-011", employeeName: "Ananya Singh",
    entityId: "ent-1", entityName: "ACME India Pvt Ltd", generatedDate: daysAgo(5),
    generatedBy: "Anita Desai", sourceModule: "Employee Request", status: "Sent",
    fileSize: "170 KB", eSigned: true },
  { id: "gd-10", generatedId: "GEN-DOC-2024-0010", documentName: "Relieving Letter — Ishaan Bose (ex-employee)",
    templateName: "Relieving Letter", employeeCode: "EMP-EX-099", employeeName: "Ishaan Bose",
    entityId: "ent-1", entityName: "ACME India Pvt Ltd", generatedDate: daysAgo(28),
    generatedBy: "Anita Desai", sourceModule: "Offboarding", status: "Downloaded",
    fileSize: "180 KB", eSigned: true },
  { id: "gd-11", generatedId: "GEN-DOC-2024-0011", documentName: "Experience Letter — Ishaan Bose",
    templateName: "Experience Letter", employeeCode: "EMP-EX-099", employeeName: "Ishaan Bose",
    entityId: "ent-1", entityName: "ACME India Pvt Ltd", generatedDate: daysAgo(28),
    generatedBy: "Anita Desai", sourceModule: "Offboarding", status: "Sent",
    fileSize: "175 KB", eSigned: true },
  { id: "gd-12", generatedId: "GEN-DOC-2024-0012", documentName: "FnF Settlement Letter — Ishaan Bose",
    templateName: "FnF Settlement Letter", employeeCode: "EMP-EX-099", employeeName: "Ishaan Bose",
    entityId: "ent-1", entityName: "ACME India Pvt Ltd", generatedDate: daysAgo(27),
    generatedBy: "Rajesh Kumar", sourceModule: "Offboarding", status: "Archived",
    fileSize: "220 KB", eSigned: false },
  { id: "gd-13", generatedId: "GEN-DOC-2024-0013", documentName: "Bulk — Confirmation Letters Q2-2024",
    templateName: "Confirmation Letter", employeeCode: "EMP-BULK-001", employeeName: "Bulk Generation (12 employees)",
    entityId: "ent-1", entityName: "ACME India Pvt Ltd", generatedDate: daysAgo(45),
    generatedBy: "Anita Desai", sourceModule: "Bulk Generation", status: "Sent",
    fileSize: "2.4 MB", eSigned: false },
  { id: "gd-14", generatedId: "GEN-DOC-2024-0014", documentName: "Promotion Letter — Kavya Patel",
    templateName: "Promotion Letter", employeeCode: "EMP-006", employeeName: "Kavya Patel",
    entityId: "ent-1", entityName: "ACME India Pvt Ltd", generatedDate: daysAgo(15),
    generatedBy: "Anita Desai", sourceModule: "Core HR", status: "Cancelled",
    fileSize: "190 KB", eSigned: false },
]

// ============================================================================
//  6. Document Logs  (18 entries — all actions + modules)
// ============================================================================
export const DOCUMENT_LOGS: DocumentLog[] = [
  { id: "log-1", timestamp: hoursAgo(1), action: "Generate", module: "Generated Documents",
    documentName: "Salary Certificate — Rahul Verma", documentId: "gd-7",
    performedBy: "System (Auto-Generated)", performedByRole: "System",
    entityId: "ent-1", entityName: "ACME India Pvt Ltd",
    details: "Auto-generated on approval of request REQ-DOC-2024-001", ipAddress: "10.0.4.21" },
  { id: "log-2", timestamp: hoursAgo(3), action: "Approve", module: "Document Requests",
    documentName: "REQ-DOC-2024-002", documentId: "dr-2",
    performedBy: "Anita Desai", performedByRole: "HR Manager",
    entityId: "ent-1", entityName: "ACME India Pvt Ltd",
    details: "Approved employment certificate request for Kavya Patel (Visa)", ipAddress: "10.0.4.55" },
  { id: "log-3", timestamp: hoursAgo(6), action: "Create", module: "Document Requests",
    documentName: "REQ-DOC-2024-008", documentId: "dr-8",
    performedBy: "Wei Lin", performedByRole: "Employee",
    entityId: "ent-4", entityName: "ACME Singapore Pte Ltd",
    details: "Draft saved for employment certificate request", ipAddress: "203.116.42.10" },
  { id: "log-4", timestamp: hoursAgo(12), action: "Upload", module: "Employee Documents",
    documentName: "Form 16 — FY 2023-24", documentId: "ed-10",
    performedBy: "Rohan Gupta", performedByRole: "Employee",
    entityId: "ent-1", entityName: "ACME India Pvt Ltd",
    details: "Uploaded Form 16 PDF (1.4 MB)", ipAddress: "10.0.4.88" },
  { id: "log-5", timestamp: daysAgo(2), action: "Verify", module: "Employee Documents",
    documentName: "Form 16 — FY 2023-24", documentId: "ed-10",
    performedBy: "Rajesh Kumar", performedByRole: "Document Admin",
    entityId: "ent-1", entityName: "ACME India Pvt Ltd",
    details: "Verified Form 16 — amounts match payroll system", ipAddress: "10.0.4.55" },
  { id: "log-6", timestamp: daysAgo(3), action: "Publish", module: "HR Documents",
    documentName: "Code of Conduct 2024", documentId: "hd-10",
    performedBy: "Anita Desai", performedByRole: "HR Manager",
    entityId: "ent-1", entityName: "ACME India Pvt Ltd",
    details: "Published v3.0 — acknowledgment due in 2 days", ipAddress: "10.0.4.55" },
  { id: "log-7", timestamp: daysAgo(4), action: "Download", module: "Generated Documents",
    documentName: "Annual Increment Letter — Aarav Sharma", documentId: "gd-5",
    performedBy: "Aarav Sharma", performedByRole: "Employee",
    entityId: "ent-1", entityName: "ACME India Pvt Ltd",
    details: "Employee downloaded increment letter", ipAddress: "10.0.4.12" },
  { id: "log-8", timestamp: daysAgo(5), action: "Email", module: "Generated Documents",
    documentName: "Annual Increment Letter — Priya Nair", documentId: "gd-6",
    performedBy: "Rajesh Kumar", performedByRole: "HR Manager",
    entityId: "ent-1", entityName: "ACME India Pvt Ltd",
    details: "Sent increment letter to priya.nair@acme.com", ipAddress: "10.0.4.55" },
  { id: "log-9", timestamp: daysAgo(6), action: "Create", module: "Document Library",
    documentName: "Custom — Bonafide Letter", documentId: "tpl-21",
    performedBy: "Anita Desai", performedByRole: "HR Manager",
    entityId: "ent-1", entityName: "ACME India Pvt Ltd",
    details: "Created draft template — Bonafide Letter v0.1", ipAddress: "10.0.4.55" },
  { id: "log-10", timestamp: daysAgo(7), action: "E-Sign", module: "Generated Documents",
    documentName: "Visa / Embassy Letter — Ananya Singh", documentId: "gd-9",
    performedBy: "Anita Desai", performedByRole: "HR Manager",
    entityId: "ent-1", entityName: "ACME India Pvt Ltd",
    details: "E-signed via Adobe Sign (provider: Adobe Sign)", ipAddress: "10.0.4.55" },
  { id: "log-11", timestamp: daysAgo(8), action: "Reject", module: "Document Requests",
    documentName: "REQ-DOC-2024-006", documentId: "dr-6",
    performedBy: "Anita Desai", performedByRole: "HR Manager",
    entityId: "ent-1", entityName: "ACME India Pvt Ltd",
    details: "Rejected — bank letter template not applicable; advised Salary Certificate", ipAddress: "10.0.4.55" },
  { id: "log-12", timestamp: daysAgo(10), action: "Preview", module: "HR Documents",
    documentName: "Employee Handbook 2024", documentId: "hd-1",
    performedBy: "Kavya Patel", performedByRole: "Employee",
    entityId: "ent-1", entityName: "ACME India Pvt Ltd",
    details: "Previewed handbook v4.2", ipAddress: "10.0.4.42" },
  { id: "log-13", timestamp: daysAgo(12), action: "Send", module: "Generated Documents",
    documentName: "Offer Letter — Fatima Al-Sayed", documentId: "gd-3",
    performedBy: "Layla Hassan", performedByRole: "HR Manager",
    entityId: "ent-2", entityName: "ACME UAE FZE",
    details: "Sent offer letter via email to fatima.sayed@acme.ae", ipAddress: "94.200.10.5" },
  { id: "log-14", timestamp: daysAgo(15), action: "Clone", module: "Document Library",
    documentName: "India Offer Letter", documentId: "tpl-1",
    performedBy: "Anita Desai", performedByRole: "HR Manager",
    entityId: "ent-1", entityName: "ACME India Pvt Ltd",
    details: "Cloned to create US Offer Letter template", ipAddress: "10.0.4.55" },
  { id: "log-15", timestamp: daysAgo(18), action: "Version Change", module: "HR Documents",
    documentName: "POSH Policy 2024", documentId: "hd-2",
    performedBy: "Anita Desai", performedByRole: "HR Manager",
    entityId: "ent-1", entityName: "ACME India Pvt Ltd",
    details: "Version bumped from v2.0 to v3.0 — added committee composition", ipAddress: "10.0.4.55" },
  { id: "log-16", timestamp: daysAgo(22), action: "Archive", module: "Generated Documents",
    documentName: "FnF Settlement Letter — Ishaan Bose", documentId: "gd-12",
    performedBy: "System", performedByRole: "System",
    entityId: "ent-1", entityName: "ACME India Pvt Ltd",
    details: "Auto-archived after 30 days post LWD", ipAddress: "127.0.0.1" },
  { id: "log-17", timestamp: daysAgo(25), action: "Delete", module: "Employee Documents",
    documentName: "Payslip — Sep 2024 (duplicate)", documentId: "ed-OLD-001",
    performedBy: "Rajesh Kumar", performedByRole: "Document Admin",
    entityId: "ent-1", entityName: "ACME India Pvt Ltd",
    details: "Deleted duplicate payslip upload — soft-deleted, retained in audit", ipAddress: "10.0.4.55" },
  { id: "log-18", timestamp: daysAgo(28), action: "Generate", module: "Generated Documents",
    documentName: "Bulk — Confirmation Letters Q2-2024", documentId: "gd-13",
    performedBy: "Anita Desai", performedByRole: "HR Manager",
    entityId: "ent-1", entityName: "ACME India Pvt Ltd",
    details: "Bulk generated 12 confirmation letters via Confirmation Letter template", ipAddress: "10.0.4.55" },
]

// ============================================================================
//  7. Entity Document Configs  (4 entity configs — full 9-step wizard data)
// ============================================================================
export const ENTITY_DOCUMENT_CONFIGS: EntityDocumentConfig[] = [
  {
    id: "edc-1", entityId: "ent-1", entityName: "ACME India Pvt Ltd",
    country: "India", state: "Maharashtra",
    defaultHeader: "ACME India Header", defaultFooter: "ACME India Footer",
    defaultTemplateGroup: "India Standard Templates",
    defaultApprovalWorkflow: "HR Manager → Entity Admin",
    defaultEmailTemplateGroup: "India Document Emails",
    documentRequestEnabled: true, eSignEnabled: true, useTenantDefault: false,
    status: "Active", effectiveFrom: daysAgo(365), effectiveTo: null, version: 3,
    defaultOfferLetter: "India Offer Letter", defaultAppointmentLetter: "India Appointment Letter",
    defaultIncrementLetter: "Annual Increment Letter", defaultPromotionLetter: "Promotion Letter",
    defaultTransferLetter: "Transfer Letter", defaultRelievingLetter: "Relieving Letter",
    defaultExperienceLetter: "Experience Letter", defaultFnFLetter: "FnF Settlement Letter",
    defaultSalaryCertificate: "Salary Certificate",
    defaultWatermark: "ACME INDIA — CONFIDENTIAL", defaultSignature: "Anita Desai — HR Manager",
    enableEmployeeDocs: true,
    mandatoryDocs: [
      { docType: "PAN Card", mandatory: true, appliesTo: "All Employees", verificationRequired: true, expiryRequired: false },
      { docType: "Aadhaar Card", mandatory: true, appliesTo: "All Employees", verificationRequired: true, expiryRequired: false },
      { docType: "Bank Proof", mandatory: true, appliesTo: "All Employees", verificationRequired: true, expiryRequired: false },
      { docType: "Photograph", mandatory: true, appliesTo: "All Employees", verificationRequired: false, expiryRequired: false },
      { docType: "Form 16", mandatory: true, appliesTo: "Confirmed Employees", verificationRequired: true, expiryRequired: false },
      { docType: "Passport", mandatory: false, appliesTo: "Onsite Travelers", verificationRequired: true, expiryRequired: true },
    ],
    allowedFileTypes: "PDF, JPG, PNG, DOCX", maxFileSize: "10 MB",
    enableHRDocs: true, publishApprovalRequired: true, defaultAcknowledgment: true,
    enableDocumentRequest: true, requestApprovalRequired: true,
    defaultApprover: "HR Owner", slaDays: 3, autoGenerateAfterApproval: true,
    approvalRequiredForPublish: true, approvalRequiredForGeneration: true,
    approvalRequiredForRequest: true, eSignProvider: "Adobe Sign",
    signatory: "Anita Desai — HR Manager",
    emailTemplateGroup: "India Document Emails",
    storageLocation: "AWS S3 — ap-south-1 (Mumbai)",
    folderStructure: "{Entity}/{Department}/{EmployeeCode}/{DocumentType}",
    fileNamingRule: "{EmployeeCode}_{DocumentType}_{YYYYMMDD}_v{Version}",
    encryptionRequired: true, retentionPeriod: "7 Years Post Exit",
  },
  {
    id: "edc-2", entityId: "ent-2", entityName: "ACME UAE FZE",
    country: "UAE", state: "Dubai",
    defaultHeader: "ACME UAE Header", defaultFooter: "ACME UAE Footer",
    defaultTemplateGroup: "UAE Standard Templates",
    defaultApprovalWorkflow: "HR Manager → Entity Admin",
    defaultEmailTemplateGroup: "UAE Document Emails",
    documentRequestEnabled: true, eSignEnabled: true, useTenantDefault: false,
    status: "Active", effectiveFrom: daysAgo(300), effectiveTo: null, version: 1,
    defaultOfferLetter: "UAE Offer Letter", defaultAppointmentLetter: "UAE Appointment Letter",
    defaultWatermark: "ACME UAE — CONFIDENTIAL", defaultSignature: "Layla Hassan — HR Manager",
    enableEmployeeDocs: true,
    mandatoryDocs: [
      { docType: "Passport", mandatory: true, appliesTo: "All Employees", verificationRequired: true, expiryRequired: true },
      { docType: "Emirates ID", mandatory: true, appliesTo: "All Employees", verificationRequired: true, expiryRequired: true },
      { docType: "Visa Page", mandatory: true, appliesTo: "All Employees", verificationRequired: true, expiryRequired: true },
      { docType: "Photograph", mandatory: true, appliesTo: "All Employees", verificationRequired: false, expiryRequired: false },
      { docType: "Bank Proof", mandatory: true, appliesTo: "All Employees", verificationRequired: true, expiryRequired: false },
    ],
    allowedFileTypes: "PDF, JPG, PNG", maxFileSize: "8 MB",
    enableHRDocs: true, publishApprovalRequired: true, defaultAcknowledgment: true,
    enableDocumentRequest: true, requestApprovalRequired: true,
    defaultApprover: "HR Owner", slaDays: 4, autoGenerateAfterApproval: true,
    approvalRequiredForPublish: true, approvalRequiredForGeneration: true,
    approvalRequiredForRequest: true, eSignProvider: "Adobe Sign",
    signatory: "Layla Hassan — HR Manager",
    emailTemplateGroup: "UAE Document Emails",
    storageLocation: "AWS S3 — me-central-1 (UAE)",
    folderStructure: "{Entity}/{Department}/{EmployeeCode}/{DocumentType}",
    fileNamingRule: "{EmployeeCode}_{DocumentType}_{YYYYMMDD}_v{Version}",
    encryptionRequired: true, retentionPeriod: "10 Years Post Exit",
  },
  {
    id: "edc-3", entityId: "ent-3", entityName: "ACME US Inc",
    country: "USA", state: "California",
    defaultHeader: "ACME US Header", defaultFooter: "ACME US Footer",
    defaultTemplateGroup: "US Standard Templates",
    defaultApprovalWorkflow: "HR Manager → Entity Admin",
    defaultEmailTemplateGroup: "US Document Emails",
    documentRequestEnabled: true, eSignEnabled: true, useTenantDefault: true,
    status: "Active", effectiveFrom: daysAgo(220), effectiveTo: null, version: 1,
    defaultOfferLetter: "US Offer Letter",
    defaultWatermark: "ACME US — CONFIDENTIAL", defaultSignature: "Sarah Johnson — HR Manager",
    enableEmployeeDocs: true,
    mandatoryDocs: [
      { docType: "SSN Card", mandatory: true, appliesTo: "All Employees", verificationRequired: true, expiryRequired: false },
      { docType: "I-9 Form", mandatory: true, appliesTo: "All Employees", verificationRequired: true, expiryRequired: false },
      { docType: "Passport / Driving License", mandatory: true, appliesTo: "All Employees", verificationRequired: true, expiryRequired: true },
      { docType: "Photograph", mandatory: true, appliesTo: "All Employees", verificationRequired: false, expiryRequired: false },
      { docType: "Bank Proof (Direct Deposit)", mandatory: true, appliesTo: "All Employees", verificationRequired: true, expiryRequired: false },
    ],
    allowedFileTypes: "PDF, JPG, PNG, DOCX", maxFileSize: "10 MB",
    enableHRDocs: true, publishApprovalRequired: true, defaultAcknowledgment: false,
    enableDocumentRequest: true, requestApprovalRequired: true,
    defaultApprover: "HR Owner", slaDays: 5, autoGenerateAfterApproval: false,
    approvalRequiredForPublish: true, approvalRequiredForGeneration: true,
    approvalRequiredForRequest: true, eSignProvider: "DocuSign",
    signatory: "Sarah Johnson — HR Manager",
    emailTemplateGroup: "US Document Emails",
    storageLocation: "AWS S3 — us-west-1 (California)",
    folderStructure: "{Entity}/{Department}/{EmployeeCode}/{DocumentType}",
    fileNamingRule: "{EmployeeCode}_{DocumentType}_{YYYYMMDD}_v{Version}",
    encryptionRequired: true, retentionPeriod: "7 Years Post Exit",
  },
  {
    id: "edc-4", entityId: "ent-4", entityName: "ACME Singapore Pte Ltd",
    country: "Singapore", state: "Singapore",
    defaultHeader: "ACME Singapore Header", defaultFooter: "ACME Singapore Footer",
    defaultTemplateGroup: "Singapore Standard Templates",
    defaultApprovalWorkflow: "HR Manager → Entity Admin",
    defaultEmailTemplateGroup: "Singapore Document Emails",
    documentRequestEnabled: true, eSignEnabled: false, useTenantDefault: true,
    status: "Active", effectiveFrom: daysAgo(180), effectiveTo: null, version: 1,
    defaultOfferLetter: "Singapore Offer Letter",
    defaultWatermark: "ACME SGP — CONFIDENTIAL", defaultSignature: "Marcus Tan — HR Manager",
    enableEmployeeDocs: true,
    mandatoryDocs: [
      { docType: "Employment Pass (EP)", mandatory: true, appliesTo: "Foreign Employees", verificationRequired: true, expiryRequired: true },
      { docType: "NRIC", mandatory: true, appliesTo: "Citizens & PRs", verificationRequired: true, expiryRequired: false },
      { docType: "Passport", mandatory: true, appliesTo: "Foreign Employees", verificationRequired: true, expiryRequired: true },
      { docType: "Photograph", mandatory: true, appliesTo: "All Employees", verificationRequired: false, expiryRequired: false },
      { docType: "Bank Proof (GIRO)", mandatory: true, appliesTo: "All Employees", verificationRequired: true, expiryRequired: false },
    ],
    allowedFileTypes: "PDF, JPG, PNG", maxFileSize: "8 MB",
    enableHRDocs: true, publishApprovalRequired: true, defaultAcknowledgment: true,
    enableDocumentRequest: true, requestApprovalRequired: true,
    defaultApprover: "HR Owner", slaDays: 4, autoGenerateAfterApproval: true,
    approvalRequiredForPublish: true, approvalRequiredForGeneration: true,
    approvalRequiredForRequest: true, eSignProvider: "—",
    signatory: "Marcus Tan — HR Manager",
    emailTemplateGroup: "Singapore Document Emails",
    storageLocation: "AWS S3 — ap-southeast-1 (Singapore)",
    folderStructure: "{Entity}/{Department}/{EmployeeCode}/{DocumentType}",
    fileNamingRule: "{EmployeeCode}_{DocumentType}_{YYYYMMDD}_v{Version}",
    encryptionRequired: true, retentionPeriod: "5 Years Post Exit",
  },
]

// ============================================================================
//  8. Mandatory Doc Presets  (12 presets — country-wise)
// ============================================================================
export const MANDATORY_DOC_PRESETS: {
  docType: string
  country: string
  mandatory: boolean
  appliesTo: string
  verificationRequired: boolean
  expiryRequired: boolean
}[] = [
  { docType: "PAN Card", country: "India", mandatory: true, appliesTo: "All Employees", verificationRequired: true, expiryRequired: false },
  { docType: "Aadhaar Card", country: "India", mandatory: true, appliesTo: "All Employees", verificationRequired: true, expiryRequired: false },
  { docType: "Bank Proof", country: "India", mandatory: true, appliesTo: "All Employees", verificationRequired: true, expiryRequired: false },
  { docType: "Form 16", country: "India", mandatory: true, appliesTo: "Confirmed Employees", verificationRequired: true, expiryRequired: false },
  { docType: "Passport", country: "India", mandatory: false, appliesTo: "Onsite Travelers", verificationRequired: true, expiryRequired: true },
  { docType: "Passport", country: "UAE", mandatory: true, appliesTo: "All Employees", verificationRequired: true, expiryRequired: true },
  { docType: "Emirates ID", country: "UAE", mandatory: true, appliesTo: "All Employees", verificationRequired: true, expiryRequired: true },
  { docType: "Visa Page", country: "UAE", mandatory: true, appliesTo: "All Employees", verificationRequired: true, expiryRequired: true },
  { docType: "SSN Card", country: "USA", mandatory: true, appliesTo: "All Employees", verificationRequired: true, expiryRequired: false },
  { docType: "I-9 Form", country: "USA", mandatory: true, appliesTo: "All Employees", verificationRequired: true, expiryRequired: false },
  { docType: "Driving License", country: "USA", mandatory: true, appliesTo: "All Employees", verificationRequired: true, expiryRequired: true },
  { docType: "Employment Pass (EP)", country: "Singapore", mandatory: true, appliesTo: "Foreign Employees", verificationRequired: true, expiryRequired: true },
]

// ============================================================================
//  9. Dashboard Stats  (computed totals)
// ============================================================================
const isExpiringSoon = (dateStr: string | null): boolean => {
  if (!dateStr) return false
  const target = new Date(dateStr)
  if (isNaN(target.getTime())) return false
  const today = new Date(); today.setHours(0, 0, 0, 0)
  target.setHours(0, 0, 0, 0)
  const diff = (target.getTime() - today.getTime()) / 86400000
  return diff >= 0 && diff <= 30
}
const isExpired = (dateStr: string | null): boolean => {
  if (!dateStr) return false
  const target = new Date(dateStr)
  if (isNaN(target.getTime())) return false
  const today = new Date(); today.setHours(0, 0, 0, 0)
  target.setHours(0, 0, 0, 0)
  return target.getTime() < today.getTime()
}

export const DASHBOARD_STATS = {
  totalDocs: EMPLOYEE_DOCUMENTS.length + HR_DOCUMENTS.length + GENERATED_DOCUMENTS.length,
  employeeDocsCount: EMPLOYEE_DOCUMENTS.length,
  hrDocsCount: HR_DOCUMENTS.length,
  templatesCount: DOCUMENT_TEMPLATES.length,
  generatedCount: GENERATED_DOCUMENTS.length,
  pendingRequests: DOCUMENT_REQUESTS.filter(
    r => r.status === "Submitted" || r.status === "Pending HR Approval" || (r.status as DocumentStatus) === "Draft"
  ).length,
  pendingHRApproval: DOCUMENT_REQUESTS.filter(r => r.status === "Pending HR Approval").length,
  pendingEmployeeUpload: EMPLOYEE_DOCUMENTS.filter(d => d.status === "Pending Upload").length,
  expiringDocs: EMPLOYEE_DOCUMENTS.filter(d => isExpiringSoon(d.expiryDate)).length,
  expiredDocs: EMPLOYEE_DOCUMENTS.filter(d => isExpired(d.expiryDate) || d.status === "Expired").length,
  rejectedDocs: DOCUMENT_REQUESTS.filter(r => r.status === "Rejected").length
    + EMPLOYEE_DOCUMENTS.filter(d => d.status === "Rejected").length,
  favouriteTemplates: DOCUMENT_TEMPLATES.filter(t => t.isFavourite).length,
}
